server:
  port: 9030

app:
  ai:
    retry-count: 3

spring:
  ai:
    openai:
      chat:
        options:
          stream-usage: true

  datasource:
    url: jdbc:postgresql://localhost:5432/promptforge_intelligence_db

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: intelligence-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: none
            connectTimeout: 2000
            readTimeout: 5000

logging:
  level:
    com.mayur: INFO
    org.springframework.cloud.openfeign: WARN
    org.springframework.cloud.openfeign.support.SpringEncoder: WARN
    feign: WARN
    org.springframework.kafka: INFO
    org.springframework.ai.chat.model.MessageAggregator: OFF
    org.springframework.ai.model.tool: DEBUG
    org.springframework.ai.tool.method: OFF
    org.springframework.ai.util.json: OFF
    com.mayur.distributed_promptforge.intelligence_service.llm.CodeGenerationTools: DEBUG
