spring:
  application:
    name: discovery-service

server.port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    response-cache-update-interval-ms: 2000

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"