spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        native:
          search-locations: file:C:/Users/mayur/Desktop/PromptForge/config-repo
  profiles:
    active: native

server.port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
